name: SonarCloud Python
on:
  push:
    branches:
main
  pull_request:
    branches:
main
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
uses: actions/checkout@v4
name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

name: SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          organization: your-org
          projectKey: your-org_your-project
          token: ${{ secrets.SONAR_TOKEN }}
