name: CI - Python Build, Test, SonarCloud Analysis

on:
  push:
    branches:
      - main
      - 'feature/**'
      # Other branch patterns you want to run CI for
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_test_analyze:
    name: Build, Test, Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # SonarCloud needs full history for accurate analysis, however, specified shallow clone this time.

      # --------------------------------------------------------------------
      # Python Environment Setup
      # --------------------------------------------------------------------
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          # sonar.python.version parameter in sonar-project.properties file.

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests and generate coverage report
        run: pytest
        
      # --------------------------------------------------------------------
      # SonarCloud Analysis
      # --------------------------------------------------------------------
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Required for Pull Request decoration
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # SonarCloud token set in GitHub Secrets

      # --------------------------------------------------------------------
      # Upload Artifacts (Optional, for inspection)
      # --------------------------------------------------------------------
      - name: Upload XML coverage report (for SonarCloud and inspection)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

      - name: Upload HTML coverage report (for local inspection)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov/
